### ISSUE TITLE
Cannot save as OGG

### ISSUE THREAD

**Issue by jammily** [godiard/fototoon-activity#17]
Can not save the project as movie (OGG).

**Comment by godiard** [comment]
Could you provide more information? What is your testing environment, screenshot and or the activity log could be useful.

**Comment by jammily** [comment]
I clic the "Save as video (OGG)" button and the activity stop working (it frezzes). I can't see any logs after doing that.

I tried on XO-1, XO-1.5, XO-1.75 and XO-4

My image is build on:
OLPC OS version 13.2.8
olpc-os-builder version v7.0.10
Built using Fedora 18
Sugar version 0.110

**Comment by quozl** [comment]
Reproduced with FotoToon-23.  There are logs, but they are not useful for the problem.

```
(sugar-activity:1882): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:564:40: Missing name of pseudo-class

(sugar-activity:1882): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:575:32: Missing name of pseudo-class

(sugar-activity:1882): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:585:32: Missing name of pseudo-class

(sugar-activity:1882): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:594:48: Missing name of pseudo-class

(sugar-activity:1882): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:725:7: Missing name of pseudo-class

(sugar-activity:1882): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:739:7: Missing name of pseudo-class

(sugar-activity:1882): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:768:7: Missing name of pseudo-class

(sugar-activity:1882): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:782:7: Missing name of pseudo-class
1504304483.079243 ERROR root: seting image_name image1.png
1504304483.123096 ERROR root: seting image_name image2.png

(sugar-activity:1882): Gdk-CRITICAL **: gdk_device_get_source: assertion `GDK_IS_DEVICE (device)' failed

(sugar-activity:1882): Gdk-CRITICAL **: gdk_device_get_source: assertion `GDK_IS_DEVICE (device)' failed
```

Workaround is to use Terminal to stop the activity.

```
sudo killall -r FotoToon
```

**Comment by quozl** [comment]
Reproduced on Fedora 18 by excluding FotoToon-23.  It isn't a problem with FotoToon-23 per se.

* prepare a series of numbered PNG files, e.g. 0.png 1.png 2.png,
* run this GStreamer pipeline from shell,
```
gst-launch-1.0 \
    multifilesrc location="%d.png" index=0 caps="image/png,framerate=(fraction)1/1" ! \
    pngdec ! videoconvert ! \
    videorate ! theoraenc ! oggmux ! filesink location="out.ogg"
```

On Ubuntu 16.04 the pipeline completes.

On Fedora 18 the pipeline hangs.  GStreamer reports "ERROR: pipeline doesn't want to preroll."

So it looks like when @samdroid-apps added ad92aaa6f8b0e2163bb773b9106e0ddf21da54cc it probably didn't get tested on Fedora 18.
